ALTER TABLE SERDE_PARAMS ADD COLUMN NEW_PARAM_VALUE CLOB;
UPDATE SERDE_PARAMS SET NEW_PARAM_VALUE = PARAM_VALUE;
ALTER TABLE SERDE_PARAMS DROP COLUMN PARAM_VALUE;
RENAME COLUMN SERDE_PARAMS.NEW_PARAM_VALUE TO PARAM_VALUE;
