#!/bin/sh
set -e

if [ \( "$1" = "purge" \) ]; then
    echo POSTRM
fi

if [ -f __PREFIX__/conf/restart/hiveserver2-__VERSION_3DIGIT__.restart ]; then
    rm -f __PREFIX__/conf/restart/hiveserver2-__VERSION_3DIGIT__.restart
fi