# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

status = ERROR
name = HiveLog4j2

# Properties
property.hive.log.level = INFO
property.hive.log.dir = /opt/mapr/hive/hive-3.1.3/logs/mapr

# Appenders
appender.hiveserver2.type = RollingRandomAccessFile
appender.hiveserver2.name = hiveserver2
appender.hiveserver2.fileName = ${sys:hive.log.dir}/mapr-hiveserver2-${hostName}.log
appender.hiveserver2.filePattern = ${sys:hive.log.dir}/mapr-hiveserver2-${hostName}.log.%d{yyyy-MM-dd}
appender.hiveserver2.layout.type = PatternLayout
appender.hiveserver2.layout.pattern = %d{ISO8601} %5p [%t] %c{2}: %m%n
appender.hiveserver2.policies.type = Policies
appender.hiveserver2.policies.time.type = TimeBasedTriggeringPolicy
appender.hiveserver2.policies.time.interval = 1

appender.metastore.type = RollingRandomAccessFile
appender.metastore.name = metastore
appender.metastore.fileName = ${sys:hive.log.dir}/mapr-metastore-${hostName}.log
appender.metastore.filePattern = ${sys:hive.log.dir}/mapr-metastore-${hostName}.log.%d{yyyy-MM-dd}
appender.metastore.layout.type = PatternLayout
appender.metastore.layout.pattern = %d{ISO8601} %5p [%t] %c{2}: %m%n
appender.metastore.policies.type = Policies
appender.metastore.policies.time.type = TimeBasedTriggeringPolicy
appender.metastore.policies.time.interval = 1

# Loggers
rootLogger.level = ${sys:hive.log.level}

# Hive Server 2 logs
logger.hs2.name = org.apache.hadoop.hive.ql.service
logger.hs2.level = info
logger.hs2.additivity = false
logger.hs2.appenderRef.hiveserver2.ref = hiveserver2

# Hive Metastore logs
logger.hmeta.name = org.apache.hadoop.hive.metastore
logger.hmeta.level = info
logger.hmeta.additivity = false
logger.hmeta.appenderRef.metastore.ref = metastore

# Common Hive logs (go to both)
logger.hive.name = org.apache.hadoop.hive
logger.hive.level = info
logger.hive.additivity = false
logger.hive.appenderRef.hiveserver2.ref = hiveserver2
